name = "sitemap-monitor"
compatibility_date = "2024-12-15"
pages_build_output_dir = ".vercel/output/static"

# KV namespaces for caching
[[kv_namespaces]]
binding = "CACHE_KV"
id = "your-cache-kv-id"
preview_id = "your-cache-kv-preview-id"

[[kv_namespaces]]
binding = "TAG_CACHE_KV"
id = "your-tag-cache-kv-id"
preview_id = "your-tag-cache-kv-preview-id"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "sitemap-monitor"
database_id = "7ac9be7e-8097-4694-a72f-0aa220bdc541" # replace with your D1 Database ID

# Queue for background tasks (optional)
[queues]
QUEUE = "sitemap-monitor-queue"
